### ISSUE TITLE
Connection of model to metabolic  model

### ISSUE THREAD

**Issue by sm1216** [HenrikCordes/isoniazid-PBPK-model#1]
Hello sir, 
Thank you for uploading the model. I am having a problem understanding how you connected the pbpk model to the metabolic model.
Would you be kind enough to share the protocol with me or schedule a meeting to show me how you connected the models? I would really appreciate the help.

Thank you, 
Sabyasachi Mohanty
Sabya.mohanty12@gmail.com

**Comment by sm1216** [comment]
Integration of genome-scale metabolic networks into whole-body PBPK models shows phenotype-specific cases of drug-induced metabolic perturbation. I have referred to this paper.

**Comment by HenrikCordes** [comment]
Hi @sm1216,

thank your for you interest and reaching out. 

Regarding the connection between the PBPK and genome scale metabolic network models (GEM):
The said Isoniazid PBPK model contains the explicit ADME reactions for the complex metabolism and transport processes
see the [Cordes et al. 2016](http://aac.asm.org/content/60/10/6134.long)

In order to link both model types, the ADME reactions consuming co-factors to metabolize and transport the drug and drug metabolites were introduced as reaction rates in the GEM (see [table 1](https://www.nature.com/articles/s41540-018-0048-1/tables/1) in the paper).

The introduced reactions in the GEM were the following:
![image](https://user-images.githubusercontent.com/4817133/208990311-de15ae63-1ee0-4424-b922-840b4d942c76.png)

Here I checkt for the respective ADME genes (for example [NAT2](https://www.ncbi.nlm.nih.gov/gene/10)) in which cellular sub compartment it is located via the uniprot annotation  (for example [NAT2](https://www.uniprot.org/uniprotkb/P11245/entry) ). The MATLAB code of how to add the reaction to the used Recon GEM is here: [addINHMetabolism2model.txt](https://github.com/HenrikCordes/isoniazid-PBPK-model/files/10280769/addINHMetabolism2model.txt)

Back in the days, the PK-Sim models could only be worked on with a MATLAB toolbox, nowadays there is only the [ospsuite R](https://github.com/Open-Systems-Pharmacology/OSPSuite-R) package. I attached the function files (.txt) that would extract the time resolved reaction rates form the PBPK model: [getDiffusionRates_INH.txt](https://github.com/HenrikCordes/isoniazid-PBPK-model/files/10280750/getDiffusionRates_INH.txt) 

Next the PBPK simulated reaction rates and the GEM containing the explicit ADME reaction rates were coupled (for each time step) using the [MOMA algorithm by Serge et al.](https://www.pnas.org/doi/10.1073/pnas.232349399). The used implementieren is here: [dMOMA.txt](https://github.com/HenrikCordes/isoniazid-PBPK-model/files/10280895/dMOMA.txt)

The resulting flux trajectories where than used to derive the results presented in [Cordes et al. 2018](https://www.nature.com/articles/s41540-018-0048-1).

All the calculations from back then (PBPK simulations and GEM modeling) were done in MATLAB. I had to convert the attached .txt files from .m files (MATALB code) or otherwise I could not upload them. You might want to rename them to .m

My coding and organization skills from back than were just "in the making" :-D 
It would take me a bit to compile all data and functions in a running scrip and due to the development of the discontinuation of the PK-Sim MATLAB toolbox one would have to rewrite that part in any case. 

I hope the way I did the coupling back than is a bit more clearer now. 

In any case let me know if this helps.
Also if you want to follow up on this or how you want to discuss how employ the method in another project let me know an we set a up google meets / zoom call to further discuss. 

Best
Henrik

**Comment by sm1216** [comment]
Thank you very much, sir. This helps. I would also like to meet you regarding using this method for another project. Kindly let me know your schedule.

Thanks,
Sabyasachi
Sabya.mohanty12@gmail.com

**Comment by sm1216** [comment]
Hello sir,
Can we meet today at 7 pm Frankfurt time?

Thanks,
Sabyasachi
sabya.mohanty12@gmail.com
